### Analysis of DTRA_AVstudy
### Requires DetailStats.csv as generated by .... <fill in blanks here>


av = read.csv("/home/jschlitt/Desktop/DropBox/ADM_all/DetailStats.csv")
summary(av)

pdf("home/jschlitt/Desktop/DropBox/ADM_all/Summary_Stats.pdf")

### Attack Rate
AR_hist = hist(av$attackRate)
n_breaks = length(AR_hist$breaks)
barplot(AR_hist$counts,names.arg=AR_hist$breaks[1:n_breaks-1],xlab="Attack Rate",ylab="Frequency",main="")



require(rpart)
tt = rpart(av$attackRate~av$ve+av$vtd+av$other+av$cwtd+av$cwl)
plot(tt)
text(tt)


dev.off()

